In [90]:
import numpy as np 

In [118]:
a=np.arange(20,24).reshape(2,2)
b=np.arange(30,34).reshape(2,2)

In [121]:
a

array([[20, 21],
       [22, 23]])

In [123]:
b

array([[30, 31],
       [32, 33]])

In [129]:
add=a+b
add

array([[50, 52],
       [54, 56]])

In [141]:
element_wise_mul=a*b
element_wise_mul

array([[600, 651],
       [704, 759]])

In [143]:
dot_product = np.dot(a, b)
dot_product

array([[1272, 1313],
       [1396, 1441]])

In [145]:
matrix_mult = a @ b
matrix_mult

array([[1272, 1313],
       [1396, 1441]])